-- Step 1: Create the database
CREATE DATABASE devpu;

-- Step 2: Connect to the devpu database
\c devpu;

-- Step 3: Create tables

-- User table
CREATE TABLE "public"."user_entity" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" character varying(255),
    "name" character varying(255),
    "username" character varying(255),
    CONSTRAINT "user_entity_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

