# docker compose -f compose.dev.yaml up --build
# https://www.reddit.com/r/nextjs/comments/1jyv6g6/comment/mpxf2v7/

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    # environment:
    #   ENV_VARIABLE: valor
    #   NEXT_PUBLIC_ENV_VARIABLE: valor
    env_file:
      - ./frontend/.env.local

