services:

  # Presentation Layer
  pr-frontend-web:
    container_name: pr-frontend-web
    build:
      context: ./pr-frontend-web
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./pr-frontend-web/app:/app/app
      - ./pr-frontend-web/public:/app/public
    env_file:
      - ./pr-frontend-web/.env
    restart: always

  # Logic Layer (business logic microservices)
  lg-users-ms:
    container_name: lg-users-ms
    build:
      context: ./lg-users-ms
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./lg-users-ms/.env
    depends_on:
      - data-users-db
    restart: always

  lg-events-ms:
    container_name: lg-events-ms
    build:
      context: ./lg-events-ms
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./lg-events-ms/.env
    depends_on:
      - data-groupexpenses-db
      - data-events-db
    restart: always

  lg-personalexpenses-ms:
    container_name: lg-personalexpenses-ms
    build:
      context: ./lg-personalexpenses-ms
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    env_file:
      - ./lg-personalexpenses-ms/.env
    depends_on:
      - data-personalexpenses-db
    restart: always

  lg-groupexpenses-ms:
    container_name: lg-groupexpenses-ms
    build:
      context: ./lg-groupexpenses-ms
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - ./lg-groupexpenses-ms/.env
    depends_on:
      - data-groupexpenses-db
      - data-events-db
    restart: always

  # Database Layer
  data-groupexpenses-db:
    container_name: data-groupexpenses-db
    build:
      context: ./data-groupexpenses-db
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    env_file:
      - ./data-groupexpenses-db/.env
    volumes:
      - data-groupexpenses-db:/data/db
    restart: unless-stopped

  data-users-db:
    container_name: data-users-db
    build:
      context: ./data-users-db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - ./data-users-db/.env
    volumes:
      - data-users-db:/var/lib/postgresql/data
    restart: unless-stopped

  data-events-db:
    container_name: data-events-db
    build:
      context: ./data-events-db
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    env_file:
      - ./data-events-db/.env
    volumes:
      - data-events-db:/var/lib/postgresql/data
    restart: unless-stopped

  data-personalexpenses-db:
    container_name: data-personalexpenses-db
    build:
      context: ./data-personalexpenses-db
      dockerfile: Dockerfile
    ports:
      - "5434:5432"
    env_file:
      - ./data-personalexpenses-db/.env
    volumes:
      - data-personalexpenses-db:/var/lib/postgresql/data
    restart: unless-stopped

  # Adminer UI
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - data-events-db
      - data-users-db
      - data-personalexpenses-db

# Volumes
volumes:
  data-groupexpenses-db:
    driver: local
  data-users-db:
    driver: local
  data-events-db:
    driver: local
  data-personalexpenses-db:
    driver: local
