apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-orch
  labels:
    app: apigateway-orch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway-orch
  template:
    metadata:
      labels:
        app: apigateway-orch
    spec:
      containers:
      - name: apigateway-orch
        image: gcr.io/swarch-cuentasclaras/cm-apigateway-orch
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PUBLIC_USERS_MICROSERVICE_URL
          valueFrom:
            secretKeyRef:
              name: apigateway-secrets
              key: PUBLIC_USERS_MICROSERVICE_URL
        - name: JWKS_URL
          valueFrom:
            secretKeyRef:
              name: apigateway-secrets
              key: JWKS_URL
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: apigateway-secrets
              key: JWT_ALGORITHM
        - name: PUBLIC_EVENTS_MICROSERVICE_URL
          valueFrom:
            secretKeyRef:
              name: apigateway-secrets
              key: PUBLIC_EVENTS_MICROSERVICE_URL
        - name: PUBLIC_PERSONAL_MICROSERVICE_URL
          valueFrom:
            secretKeyRef:
              name: apigateway-secrets
              key: PUBLIC_PERSONAL_MICROSERVICE_URL
        - name: PUBLIC_EXPENSES_MICROSERVICE_URL
          valueFrom:
            secretKeyRef:
              name: apigateway-secrets
              key: PUBLIC_EXPENSES_MICROSERVICE_URL
        - name: EXPENSES_GRAPHQL_URL
          valueFrom:
            secretKeyRef:
              name: apigateway-secrets
              key: EXPENSES_GRAPHQL_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-orch-service
  labels:
    app: apigateway-orch
spec:
  selector:
    app: apigateway-orch
  ports:
  - port: 80
    targetPort: 8000
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apigateway-orch-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apigateway-orch
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
