apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-ms
  labels:
    app: events-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-ms
  template:
    metadata:
      labels:
        app: events-ms
    spec:
      containers:
      - name: events-ms
        image: gcr.io/swarch-cuentasclaras/lg-events-ms
        ports:
        - containerPort: 8083
          name: http
        env:
        - name: POSTGRES_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: events-ms-secrets
              key: POSTGRES_SUPERUSER
        - name: POSTGRES_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: events-ms-secrets
              key: POSTGRES_SUPERUSER_PASSWORD
        - name: COMMUNITY_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: events-ms-secrets
              key: COMMUNITY_DATASOURCE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: events-ms-service
  labels:
    app: events-ms
spec:
  selector:
    app: events-ms
  ports:
  - port: 80
    targetPort: 8083
    name: http
  type: ClusterIP