apiVersion: apps/v1
kind: Deployment
metadata:
  name: groupexp-ms
  labels:
    app: groupexp-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groupexp-ms
  template:
    metadata:
      labels:
        app: groupexp-ms
    spec:
      containers:
      - name: groupexp-ms
        image: gcr.io/swarch-cuentasclaras/lg-groupexpenses-ms
        ports:
        - containerPort: 8085
          name: http
        env:
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: groupexp-ms-secrets
              key: SPRING_DATA_MONGODB_URI
        - name: MONGO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: groupexp-ms-secrets
              key: MONGO_ROOT_USER
        - name: MONGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: groupexp-ms-secrets
              key: MONGO_ROOT_PASSWORD
        - name: MONGO_INITIAL_DB
          valueFrom:
            secretKeyRef:
              name: groupexp-ms-secrets
              key: MONGO_INITIAL_DB
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: groupexp-ms-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: groupexp-ms-secrets
              key: RABBITMQ_PASS
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: groupexp-ms-service
  labels:
    app: groupexp-ms
spec:
  selector:
    app: groupexp-ms
  ports:
  - port: 80
    targetPort: 8085
    name: http
  type: ClusterIP
