apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-frontend-web
  labels:
    app: pr-frontend-web
spec:
  selector:
    matchLabels:
      app: pr-frontend-web
  template:
    metadata:
      labels:
        app: pr-frontend-web
    spec:
      containers:
      - name: pr-frontend-web
        image: gcr.io/swarch-cuentasclaras/pr-frontend-web:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: API_GATEWAY_URL
          valueFrom:
            secretKeyRef:
              name: frontend-web-secrets
              key: API_GATEWAY_URL
        - name: NEXT_PUBLIC_BASE_URL
          valueFrom:
            secretKeyRef:
              name: frontend-web-secrets
              key: NEXT_PUBLIC_BASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: pr-frontend-web-service
  labels:
    app: pr-frontend-web
spec:
  selector:
    app: pr-frontend-web
  ports:
  - port: 80
    targetPort: 3000
    name: http
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 34.75.103.42/32
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pr-frontend-web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pr-frontend-web
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50