apiVersion: v1
kind: Pod
metadata:
  name: test-connectivity
spec:
  containers:
  - name: test
    image: nicolaka/netshoot
    command: ["/bin/sh"]
    args: ["-c", "sleep infinity"]
  restartPolicy: Always