import os
from dotenv import load_dotenv

load_dotenv()  

JWKS_URL = os.getenv("JWKS_URL")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "RS256")

USERS_SERVICE_URL    = os.getenv("PUBLIC_USERS_MICROSERVICE_URL")

#PUBLIC_USERS_MICROSERVICE_PUBLIC_URL = os.getenv("PUBLIC_USERS_MICROSERVICE_PUBLIC_URL")

EVENTS_SERVICE_URL   = os.getenv("PUBLIC_EVENTS_MICROSERVICE_URL")
EXPENSES_SERVICE_URL = os.getenv("PUBLIC_EXPENSES_MICROSERVICE_URL")
PERSONAL_SERVICE_URL = os.getenv("PUBLIC_PERSONAL_MICROSERVICE_URL")
EXPENSES_GRAPHQL_URL = os.getenv("EXPENSES_GRAPHQL_URL")

GATEWAY_PORT = 8000
