-- Step 1: Create the database
CREATE DATABASE devpc;

-- Step 2: Connect to the devpc database
\c devpc;

-- Step 3: Create tables

CREATE TABLE "public"."event_entity" (
    "begin_date" date,
    "end_date" date,
    "invitation_enabled" boolean NOT NULL,
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "creator_id" character varying(255),
    "description" character varying(255),
    "invitation_code" character varying(255),
    "name" character varying(255),
    CONSTRAINT "event_entity_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


CREATE TABLE "public"."event_participants_entity" (
    "event_id" bigint,
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "participant_id" character varying(255),
    CONSTRAINT "event_participants_entity_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


CREATE TABLE "public"."expense_entity" (
    "event_id" bigint,
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "creator_id" character varying(255),
    "external_doc_id" character varying(255),
    CONSTRAINT "expense_entity_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


ALTER TABLE ONLY "public"."event_participants_entity" ADD CONSTRAINT "fklym35g1qao4h9oyul7yjokajj" FOREIGN KEY (event_id) REFERENCES event_entity(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."expense_entity" ADD CONSTRAINT "fkn65bdngnfiohqb0v9purfch5c" FOREIGN KEY (event_id) REFERENCES event_entity(id) NOT DEFERRABLE;