-- Step 1: Create the database
CREATE DATABASE devpp;

-- Step 2: Connect to the devpp database
\c devpp;

-- Step 3: Create tables

-- PersonalExpenses table
CREATE TABLE "public"."personal_expense_entity" (
    "date" date,
    "total" real,
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "owner" bigint,
    "concept" character varying(255),
    "type" character varying(255),
    CONSTRAINT "personal_expense_entity_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "personal_expense_entity_type_check" CHECK ((type)::text = ANY ((ARRAY['COMIDA_Y_BEBIDA'::character varying, 'COMPRAS'::character varying, 'HOGAR'::character varying, 'TRANSPORTE'::character varying, 'ENTRETENIMIENTO'::character varying, 'COMUNICACION'::character varying, 'GASTOS_FINANCIEROS'::character varying])::text[]))
) WITH (oids = false);

