import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { SessionProvider } from '@/contexts/SessionContext';
import { getSession } from '@/lib/getSession';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    initialScale: 1,
    width: "device-width",
    height: "device-height",
  }
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Precargar la sesión del servidor para hidratar el cliente
  const initialSession = await getSession();
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background h-dvh w-dvw relative flex flex-col` }
      >
        <SessionProvider initialSession={initialSession}>
          {children}
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
